### ISSUE TITLE
Add VK band plans

### ISSUE THREAD

**Issue by vk3il** [camilstaps/SODA-POP-source#14]
Will do this once the generic IARU ones are done

**Comment by camilstaps** [comment]
Perhaps the easiest would be to change the `enum band` definition. This was also needed for IARU-3, which does not have 60m. So you could create `BAND_80A` and `BAND_80B`. However, it may not be that convenient to use because you'd have to go into the RIT menu to change the band when you want to change to the other side of the 80m band.

A nicer way would be to change `fix_op_freq()` in `SODA_POP.ino`. This fixes the operating frequency between the band limits. You can make special cases there: if the operating frequency is in the forbidden part of the 80m band, and on the lower side, you can change it to the boundary of the higher side; if on the higher side, change to the lower side. (This should all be in an `#ifdef PLAN_VK`.)

**Comment by vk3il** [comment]
Implemented and tested OK
